-- Driver: dumps every important table as INSERT statements wrapped with
-- IDENTITY_INSERT toggles and DELETE-before-INSERT guards for idempotency.
-- Output is captured to a single Seed_DataDump.sql via sqlcmd -o.

SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;

-- ── Temp scripter procedure (dropped at the end) ────────────────────────────
IF OBJECT_ID('tempdb..#exists') IS NOT NULL DROP TABLE #exists;
SELECT 1 AS x INTO #exists;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Tool_GenerateInserts
    @TableName SYSNAME,
    @Schema    SYSNAME = N'dbo'
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @col_list NVARCHAR(MAX) = STUFF((
        SELECT N', ' + QUOTENAME(COLUMN_NAME)
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = @TableName AND TABLE_SCHEMA = @Schema
        ORDER BY ORDINAL_POSITION
        FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 2, '');

    DECLARE @value_expr NVARCHAR(MAX) = STUFF((
        SELECT N' + '', '' + ' +
            CASE
              WHEN DATA_TYPE IN ('int','bigint','smallint','tinyint','decimal','numeric','bit','float','real','money','smallmoney')
                THEN N'ISNULL(CONVERT(NVARCHAR(50), ' + QUOTENAME(COLUMN_NAME) + N'), N''NULL'')'
              WHEN DATA_TYPE IN ('date','datetime','datetime2','smalldatetime')
                THEN N'CASE WHEN ' + QUOTENAME(COLUMN_NAME) + N' IS NULL THEN N''NULL'' ELSE N'''''''' + CONVERT(NVARCHAR(33), ' + QUOTENAME(COLUMN_NAME) + N', 121) + N'''''''' END'
              WHEN DATA_TYPE = 'uniqueidentifier'
                THEN N'CASE WHEN ' + QUOTENAME(COLUMN_NAME) + N' IS NULL THEN N''NULL'' ELSE N'''''''' + CONVERT(NVARCHAR(36), ' + QUOTENAME(COLUMN_NAME) + N') + N'''''''' END'
              ELSE
                N'CASE WHEN ' + QUOTENAME(COLUMN_NAME) + N' IS NULL THEN N''NULL'' ELSE N''N'''''' + REPLACE(CAST(' + QUOTENAME(COLUMN_NAME) + N' AS NVARCHAR(MAX)), N'''''''', N'''''''''''') + N'''''''' END'
            END
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = @TableName AND TABLE_SCHEMA = @Schema
        ORDER BY ORDINAL_POSITION
        FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 9, '');

    DECLARE @has_identity BIT = CASE WHEN OBJECTPROPERTY(OBJECT_ID(QUOTENAME(@Schema) + '.' + QUOTENAME(@TableName)), 'TableHasIdentity') = 1 THEN 1 ELSE 0 END;
    DECLARE @qual NVARCHAR(300) = QUOTENAME(@Schema) + N'.' + QUOTENAME(@TableName);

    PRINT N'-- ─── ' + @TableName + N' ───────────────────────────────────────────';
    PRINT N'DELETE FROM ' + @qual + N';';
    IF @has_identity = 1 PRINT N'SET IDENTITY_INSERT ' + @qual + N' ON;';

    DECLARE @sql NVARCHAR(MAX) =
        N'SELECT N''INSERT INTO ' + @qual + N' (' + @col_list + N') VALUES ('' + ' + @value_expr + N' + N'');'' FROM ' + @qual + N';';
    EXEC sp_executesql @sql;

    IF @has_identity = 1 PRINT N'SET IDENTITY_INSERT ' + @qual + N' OFF;';
    PRINT N'GO';
    PRINT N'';
END
GO

-- ── Output header ──────────────────────────────────────────────────────────
PRINT N'-- Seed_DataDump.sql — auto-generated by scripts/generate-seed-dump.sql';
PRINT N'-- Captures every row in the live DB at dump time.';
PRINT N'-- To restore: run after the SSDT publish has created the schema.';
PRINT N'--   sqlcmd -S <server> -E -d ShopNShop_db -b -I -i Seed_DataDump.sql';
PRINT N'';
PRINT N'SET NOCOUNT ON;';
PRINT N'SET QUOTED_IDENTIFIER ON;';
PRINT N'GO';
PRINT N'';
PRINT N'-- Disable triggers so audit tables don''t balloon during the dump';
PRINT N'EXEC sp_msforeachtable ''DISABLE TRIGGER ALL ON ?'';';
PRINT N'GO';
PRINT N'';
PRINT N'-- Clear children first so DELETE/INSERT loops respect FKs';
PRINT N'DELETE FROM dbo.ReviewImages;';
PRINT N'DELETE FROM dbo.Reviews;';
PRINT N'DELETE FROM dbo.OrderItems;';
PRINT N'DELETE FROM dbo.Orders;';
PRINT N'DELETE FROM dbo.WalletTransactions;';
PRINT N'DELETE FROM dbo.Wallets;';
PRINT N'DELETE FROM dbo.Cart;';
PRINT N'DELETE FROM dbo.Wishlist;';
PRINT N'DELETE FROM dbo.Notifications;';
PRINT N'DELETE FROM dbo.SearchLogs;';
PRINT N'DELETE FROM dbo.ProductViewLogs;';
PRINT N'DELETE FROM dbo.RecentlyViewed;';
PRINT N'DELETE FROM dbo.PriceHistory;';
PRINT N'DELETE FROM dbo.ProductSpecifications;';
PRINT N'DELETE FROM dbo.ProductImages;';
PRINT N'DELETE FROM dbo.ProductVariants;';
PRINT N'DELETE FROM dbo.ProductSubCategories;';
PRINT N'DELETE FROM dbo.Products;';
PRINT N'DELETE FROM dbo.SellerDocuments;';
PRINT N'DELETE FROM dbo.SellerBrandMappings;';
PRINT N'DELETE FROM dbo.SellerAnalyticsDaily;';
PRINT N'DELETE FROM dbo.Sellers;';
PRINT N'DELETE FROM dbo.UserAddresses;';
PRINT N'DELETE FROM dbo.RefreshTokens;';
PRINT N'DELETE FROM dbo.OtpVerifications;';
PRINT N'DELETE FROM dbo.Users WHERE UserId > 0;';
PRINT N'DELETE FROM dbo.Coupons;';
PRINT N'DELETE FROM dbo.Offers;';
PRINT N'DELETE FROM dbo.BankOffers;';
PRINT N'DELETE FROM dbo.FooterContent;';
PRINT N'DELETE FROM dbo.HomeSections;';
PRINT N'DELETE FROM dbo.Banners;';
PRINT N'DELETE FROM dbo.Stores;';
PRINT N'DELETE FROM dbo.Pincodes;';
PRINT N'DELETE FROM dbo.AuditLogs;';
PRINT N'DELETE FROM dbo.SubCategories;';
PRINT N'DELETE FROM dbo.Categories;';
PRINT N'DELETE FROM dbo.Menus;';
PRINT N'DELETE FROM dbo.Brands;';
PRINT N'DELETE FROM dbo.GenderTypes;';
PRINT N'DELETE FROM dbo.Roles;';
PRINT N'GO';
PRINT N'';

-- ── Insert in FK-safe order ─────────────────────────────────────────────────
-- Users must come before any table whose CreatedBy/UpdatedBy/CreatedByUserId FK
-- references Users — i.e. nearly everything. Order is: roots → lookup tables →
-- Users → reference data → Sellers → catalog → transactional.
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Roles';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'GenderTypes';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Users';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Menus';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Categories';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'SubCategories';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Brands';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Pincodes';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Stores';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Banners';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'HomeSections';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'FooterContent';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'BankOffers';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Offers';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Coupons';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'UserAddresses';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Sellers';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Products';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'ProductVariants';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'ProductImages';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'ProductSpecifications';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Wallets';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Orders';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'OrderItems';
EXEC dbo.usp_Tool_GenerateInserts @TableName = 'Reviews';

-- ── Footer ─────────────────────────────────────────────────────────────────
PRINT N'';
PRINT N'-- Re-enable triggers';
PRINT N'EXEC sp_msforeachtable ''ENABLE TRIGGER ALL ON ?'';';
PRINT N'GO';
PRINT N'';
PRINT N'PRINT N''Seed_DataDump.sql complete.'';';

DROP PROCEDURE dbo.usp_Tool_GenerateInserts;
